### ISSUE TITLE
Rename dummy_call to is_authenticated

### ISSUE THREAD

**Issue by okin** [stdevel/katprep#102]
**Is your feature request related to a problem? Please describe.**
Working on some tests I noticed that the clients have a `dummy_call` function that is a real function. The name suggests that it doesn't do anything but in fact it is used to check if authentication on a system was successful. I find the name unfortunately misleading.

**Describe the solution you'd like**
Instead of having a `dummy_call` function I'd like it to be named something like `is_authenticated`.
This gives everyone a good idea what it is about.

**Describe alternatives you've considered**
Having a shorter name like just `authenticated` would work aswell but I think having the _is_ prefix does make reading code just a little bit nicer.

**Comment by pfelwor** [comment]
I agree and just opened a pull request - let me know, if this gets your point

**Comment by stdevel** [comment]
Fixed in commit 5a6bbf64e59093cf8316f886b178228b6f3dd05f - thanks again, @pfelwor! 👍
