### ISSUE TITLE
Python 3.5.2 support?

### ISSUE THREAD

**Issue by ljudva** [stdevel/katprep#117]
Hi

Just a quick question, is 3.5.2. supported or only 3.4?

Thanks

**Comment by stdevel** [comment]
HI @ljudva!
Good question, I never tried to run it on 3.4.

I suggest you give it a try - if the support is missing, we can take this issue to make katprep support version 3.5.x.

What do you think?

**Comment by rapgro** [comment]
Well, Fedora starts to enforce python 3.8, is there any plan for a new release?

**Comment by rapgro** [comment]
Python3 support is initiated:
https://github.com/stdevel/katprep/commit/936f467cd050aa9a710c46b5424e56b7139f2c13

**Comment by stdevel** [comment]
I need to test whether it is working on Python 3.8 - as you said, basic Python 3.x support was already started to implement.

**Comment by rapgro** [comment]
Well, someone should try to build latest sources in Fedora to see if it works with Python 3.8

**Comment by okin** [comment]
With #121 the most fixes proposed by 2to3 are applied.

If an error comes up I'd say open a ticket with the error message and traceback and I'll have a look!
