### ISSUE TITLE
Remove Python 2.7 support

### ISSUE THREAD

**Issue by stdevel** [stdevel/katprep#125]
As Python 2.7.x is EOL and the most Linux distributions and many projects already dropped support, we should do the same and use Python 3.6.

**Comment by stdevel** [comment]
Some tasks that need to be done:

- [ ] remove `future` imports
- [ ] remove `raw_input` calls
- [ ] reformat logging (*remove `format()` calls*)
- [ ] replace `next()` iterations

**Comment by okin** [comment]
We should also update the `classifiers` in `setup.py` if we drop support for Python 2.

**Comment by stdevel** [comment]
This is/was implemented in `43-feat-uyuni_support`.
