### ISSUE TITLE
Authconfig not working in Python 3.6

### ISSUE THREAD

**Issue by stdevel** [stdevel/katprep#150]
**Describe the bug**
It looks like encrypted authentication containers are not working in Python 3.x

**To Reproduce**
1. Create an authconfig file using `katprep_authconfig`
2. Try to list entries using `katprep_authconfig <filename> list`

**Expected behavior**
Credentials are printed on the screen.

**Environment (please complete the following information):**
 - OS version: Pop!_OS 20.04

**Additional context**
-

**Comment by stdevel** [comment]
Investigating in branch `150-bug-authconfig_python3`

**Comment by okin** [comment]
Fixed by #151
