### ISSUE TITLE
Downtime in Nagios/Icinga 1.x gets only activated for hosts, not for their services

### ISSUE THREAD

**Issue by AnonJo** [stdevel/katprep#41]
While using katprep_maintenance ... prepare the downtime for Nagios/Icinga 1.x hosts gets only activated for hosts, not for their services.

**Comment by stdevel** [comment]
Verified environment:
- OMD 2.6.0 (*Icinga 1.14.0*)
- Red Hat Enterprise Linux 6.9 (*x86_64*)

Looks like CGI call parameter `cmd_typ` was changed from 55 to 86.

**Comment by stdevel** [comment]
Figured out some additional problems with Nagios 3.x - CGI cmds differ between Icinga 1.x and Nagios 3.x:

| Command | Nagios | Icinga |
|:------------ |:--------|:------- |
| Schedule downtime for host | 55 (*host*) and 86 (*services*) | 86 (*host and services*) |
| Unschedule downtime for host | not possible | 171 (*host and services*) |
| Schedule downtime for hostgroup (*host and services*) | 85 | 85 |
| Unschedule downtime for hostgroup | not possible | not possible |

**Comment by stdevel** [comment]
Need to auto-detect Nagios installations in order to make `__manage_downtime()` aware of additional or missing calls.

**Comment by stdevel** [comment]
Bug fixed for Icinga 1.x in commit 7eb696a10efcc3d4a8f77937bca7cc8c73a7e8f1.

**Comment by stdevel** [comment]
Fixed webs-crap-ping for Nagios, adjusted `get_services()` return for `katprep_populate` in commit cb3e6799ffbd7fff46216c5515ac059a6745e7c1.
