### ISSUE TITLE
Change license for customer-/company-sensitive code?

### ISSUE THREAD

**Issue by stdevel** [stdevel/katprep#95]
Customer/company specific customization to the core code is currently difficult as the GPLv3 license requires to contribue _all_ the changed code upstream. For some customers/companies this can be an issue. So maybe chaning the license (*e.g. APL*) might be an option.

**Comment by okin** [comment]
Would having a system that makes use of hooks to use custom code being a better choice?
I would rather not sacrifice an rather open license because some customer has problems with improving open source software while they don't have a problem with using it.

**Comment by stdevel** [comment]
Implementing hooks would be a decent option!
